### ISSUE TITLE
Add P. 56 sample code to eratta

### ISSUE THREAD

**Issue by potato4d** [potato4d/nuxt-beginners-guide#2]
state.users[user.id] であるべき箇所が state.user[user.id] となっている。

**Comment by hilarious23** [comment]
P. 56  
```
getters: {
...
  },
  mutations: {
    ...
    },
```

gettersとmutationsの間の " , "が抜けているようですので一応ご連絡させていただきます！

**Comment by potato4d** [comment]
@hilarious23 
ありがとうございます！確認します。

**Comment by potato4d** [comment]
resolved.
