### ISSUE TITLE
タイポを見つけました

### ISSUE THREAD

**Issue by koji-kimura** [potato4d/nuxt-beginners-guide#3]
はじめまして。
こちらの書籍のkindle版でタイポを見つけたのでその連絡です。
mutationsの手前に「,」が抜けてました。
（githubのコードは問題なかったです）

ご確認よろしくお願いします。

![2018-11-21 19 58 37](https://user-images.githubusercontent.com/37994567/48837152-e1f4ed00-edc7-11e8-84c7-cf1ad4f553a9.png)

**Comment by potato4d** [comment]
ありがとうございます！修正済みです。
