### ISSUE TITLE
P92の記載について

### ISSUE THREAD

**Issue by retasretas** [potato4d/nuxt-beginners-guide#4]
P92のcreate-nuxt-appで出来上がった後のディレクトリ構造について
node_modulesディレクトリについて、package.jsonと同一の階層のままにするという記載がなかったため、app以下へ移動してしまいしばらくハマってしまいましたので、そういった記載があるとハマる人が少なくなって親切かと思いました。

**Comment by potato4d** [comment]
FB ありがとうございます！増刷の際に参考とさせていただきます！

**Comment by TakumaKurosawa** [comment]
@retasretas  さん）
僕も同じところでめっちゃ悩みました！ありがとうございました！
