### ISSUE TITLE
4章のnuxt-blog-serviceで投稿のないユーザで投稿一覧を表示するとエラーになる

### ISSUE THREAD

**Issue by WO8TimeSpace175ZERO2** [potato4d/nuxt-beginners-guide#6]
nuxt-blog-serviceの「app\store\posts.js」のfetchPostsアクションメソッドですが、
ログインしたユーザーに投稿が存在しない場合、
const posts = await this.$axios.$get(`/posts.json`)
実行直後のpostsがnullになっているのではないでしょうか。
そのため、Object.entries(posts).reverse().forEach(・・・
のところでエラーが発生するのではないかと存じます。
投稿が0件の場合の対応が必要ではないでしょうか。

**Comment by potato4d** [comment]
https://github.com/potato4d/nuxt-beginners-guide/issues/5 と重複しているようなのでこちらで調査します。
